import React, { Component } from "react";
import ButtonGroup from "react-bootstrap/ButtonGroup";
import Button from "react-bootstrap/Button";
import axios from 'axios';
import Papa from 'papaparse';
import "./App.css";
//import myData from './recipes.json';

import myData from './recipes.json';
import csvdata from './data_csv'
//const API_URL = "https://b436-20-120-216-46.ngrok.io/search";

import { useState } from 'react'
import MultiSelect from  'react-multiple-select-dropdown-lite'
import  'react-multiple-select-dropdown-lite/dist/index.css'

const data = [{ value:'One', selected:true }, { value: 'Two' }, { value:'Three' }]

//var myData = []

export default class App extends Component {
  constructor(props) {
    super();
    this.state = {
      list: true,
      gotData: false,
      newData : [],
      ingredients : [],
      tags : [],
      ingredients_ex : [],
      tags_ex : []
    };
    this.newData = myData;
    console.log(csvdata.optionsTags)
  }
  
 componentDidMount() {
    const requestOptions = {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        "ingredients": [
           "beans"
        ],
        "tags": [
          "turkish"
        ],
        "ingredient_exclusions": [
           ""
        ],
        "tag_exclusions": [
          ""
        ]
       
     })
  };

  /*
    fetch("https://4c3f-20-120-216-46.ngrok.io/search",requestOptions)
        console.log('test priti')
        //console.log(responseJson)
        
        //console.log(this.newData);
        this.newData = responseJson;
        console.log(this.newData);
        this.setState({ gotData: true });
        console.log(this.gotData);
        //myData = responseJson;
        console.log('test2 priti')
      });
      
      */
      
  }
  /*showCard = id => {
  
    this.setState({
      list: false,
      card: true
    });
  };*/

  /*showList = () => {
    this.setState({
      card: false,
      list: true
    });
  };*/
  
  handleOnchangeFirst  =  val  => {
    console.log(val);
    this.ingredients = val;
  }

  handleOnchangeSecond  =  val  => {
    console.log(val);
    this.tags = val;
  }
  handleOnchangeThird  =  val  => {
    console.log(val);
    this.ingredients_ex = val;
  }

  handleOnchangeFourth  =  val  => {
    console.log(val);
    this.tags_ex = val;
  }
  handleClick = val => {
    console.log(this.tags);
    console.log(this.ingredients);
    this.launchSearch()
  }

  launchSearch () {
    
    var ing = [];
    var tags = [];
    var ing_ex = [];
    var tags_ex = [];
    var str_array = this.ingredients.split(',');
    
    for(var i = 0; i < str_array.length; i++) {
      // Trim the excess whitespace.
      str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
      // Add additional code here, such as:
      //alert(str_array[i]);
      ing.push(str_array[i]);
    }

    str_array = this.tags.split(',');
    
    for(var i = 0; i < str_array.length; i++) {
      // Trim the excess whitespace.
      str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
      // Add additional code here, such as:
      //alert(str_array[i]);
      tags.push(str_array[i]);
    }

    str_array = this.tags_ex.split(',');
    
    for(var i = 0; i < str_array.length; i++) {
      // Trim the excess whitespace.
      str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
      // Add additional code here, such as:
      //alert(str_array[i]);
      tags_ex.push(str_array[i]);
    }

    str_array = this.ingredients_ex.split(',');
    
    for(var i = 0; i < str_array.length; i++) {
      // Trim the excess whitespace.
      str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
      // Add additional code here, such as:
      //alert(str_array[i]);
      ing_ex.push(str_array[i]);
    }

    console.log(ing);
    const requestOptions = {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        "ingredients": ing,
        "tags": tags,
        "ingredient_exclusions": ing_ex,
        "tag_exclusions": tags_ex
       
     })
  };
    fetch("https://43a7-20-120-216-46.ngrok.io/search",requestOptions)
      .then(response => response.json())
      .then(responseJson => {
        //this.setState({ players: responseJson.data });
        console.log('test priti')
        //console.log(responseJson)
        
        //console.log(this.newData);
        this.newData = responseJson;
        console.log(this.newData);
        this.setState({ gotData: true });
        console.log(this.gotData);
        //myData = responseJson;
        console.log('test2 priti')
      });
      
  }

  options  = [
    { label:  'Option 1', value:  'option_1'  },
    { label:  'Option 2', value:  'option_2'  },
    { label:  'Option 3', value:  'option_3'  },
    { label:  'Option 4', value:  'option_4'  },
  ]


  render() {

    console.log("preeti s0");
    console.log(this.newData);
    if (this.newData) {
      console.log("preeti s1");
      //myData = this.newData;
      console.log("preeti s2");
    }
   
    return (
      <>
  
  <div>
    <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand d-flex align-items-center">
           <strong>Smart Recipe Recommendation Engine</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">
    
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Choose Recipe Options</h1>
          <br>
          </br>
          <p>
          <div class="btn-group flex-wrap" >
            <MultiSelect
        onChange={this.handleOnchangeFirst}
        options={this.optionsIng}
        placeholder = "Select Ingredients"


      />
      <MultiSelect 
        onChange={this.handleOnchangeSecond}
        options={this.optionsTags}
        placeholder = "Select Tags"
      />
      </div>
      <div class="btn-group flex-wrap" >
       <MultiSelect
        onChange={this.handleOnchangeThird}
        options={this.optionsIng}
        placeholder = "Exclude Ingredients"


      />
      <MultiSelect 
        onChange={this.handleOnchangeFourth}
        options={this.optionsTags}
        placeholder = "Exclude Tags"
      />
     
      </div>
      <br>
     </br>
     <br>
     </br>
     <br>
     </br>
      {"  "}<Button variant="primary" onClick = {this.handleClick}>Search Recipe</Button>
         </p>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">

        { 
        this.newData.neighbors.map((data, key) => {
          return (
            <>
             <div class="col-md-4">
             <div class="card mb-4 box-shadow">
               <img class="card-img-top" src={data[0].image} alt="Card image cap"/> 
               {console.log(data[0].image)}
               <div class="card-body">
               <blockquote class="blockquote mb-1">
               <strong>
                 <p class="card-text justify-content-md-center">{data[0].name}</p>
                 </strong>
                 </blockquote >
                 <p class="card-text">{data[0].description}</p>
                 <blockquote class="blockquote mb-1">
                 <strong>
                 <p class="card-text justify-content-md-center">Ingredients:</p>
                 </strong>
                 </blockquote >
                 {data[0].ingredients.map((dataIn, key) => {
          return (
            <>
             <p class="card-text justify-content-md-center">{dataIn}</p>
            </>
                 );
          
        })} 
                 
                 <blockquote class="blockquote mb-1" font-weight="bold">
                   <strong>
                 <p class="card-text">Steps:</p>
                 </strong>
                 </blockquote >
                 <p class="card-text">{data[0].steps}</p>
                 <p class="card-text">Calories:  {data[0].cal} Carbs: {data[0].carbs}</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <small class="text-muted">Prep Time (Minutes)</small>
                   <small class="text-muted">{data[0].minutes}</small>
                 </div>
               </div>
             </div>
             </div>
           </>
          );
          
        })} 
          </div>
        </div>
      </div>

    </main>
    </div>
        </>
    );
  }

  optionsIng  = [
    { label: "low-fat" , value: "low-fat" },
    { label: "butternut" , value: "butternut" },
    { label: "frosting" , value: "frosting" },
    { label: "low-fat" , value: "low-fat" },
    { label: "self" , value: "self" },
    { label: "cream" , value: "cream" },
    { label: "ginger" , value: "ginger" },
    { label: "beans" , value: "beans" },
    { label: "strawberry" , value: "strawberry" },
    { label: "jarlsberg" , value: "jarlsberg" },
    { label: "iceberg" , value: "iceberg" },
    { label: "caponata" , value: "caponata" },
    { label: "guar" , value: "guar" },
    { label: "chicken" , value: "chicken" },
    { label: "canadian" , value: "canadian" },
    { label: "low-sodium" , value: "low-sodium" },
    { label: "fat-free" , value: "fat-free" },
    { label: "courgette" , value: "courgette" },
    { label: "italian" , value: "italian" },
    { label: "unsweetened" , value: "unsweetened" },
    { label: "ground" , value: "ground" },
    { label: "casserole" , value: "casserole" },
    { label: "monkfish" , value: "monkfish" },
    { label: "brewed" , value: "brewed" },
    { label: "goat" , value: "goat" },
    { label: "cheesecloth" , value: "cheesecloth" },
    { label: "diced" , value: "diced" },
    { label: "citrus" , value: "citrus" },
    { label: "smoked" , value: "smoked" },
    { label: "barbecue" , value: "barbecue" },
    { label: "imitation" , value: "imitation" },
    { label: "margarita" , value: "margarita" },
    { label: "marrow" , value: "marrow" },
    { label: "matcha" , value: "matcha" },
    { label: "english" , value: "english" },
    { label: "meatloaf" , value: "meatloaf" },
    { label: "rice" , value: "rice" },
    { label: "marjoram" , value: "marjoram" },
    { label: "melon" , value: "melon" },
    { label: "mesquite" , value: "mesquite" },
    { label: "blue" , value: "blue" },
    { label: "hot" , value: "hot" },
    { label: "red" , value: "red" },
    { label: "suet" , value: "suet" },
    { label: "soft" , value: "soft" },
    { label: "dry" , value: "dry" },
    { label: "fat" , value: "fat" },
    { label: "unbaked" , value: "unbaked" },
    { label: "monkfish" , value: "monkfish" },
    { label: "mung" , value: "mung" },
    { label: "unsweetened" , value: "unsweetened" },
    { label: "adzuki" , value: "adzuki" },
    { label: "cheddar" , value: "cheddar" },
    { label: "northern" , value: "northern" },
    { label: "russet" , value: "russet" },
    { label: "jalapeno" , value: "jalapeno" },
    { label: "low" , value: "low" },
    { label: "chicken" , value: "chicken" },
    { label: "top" , value: "top" },
    { label: "frying" , value: "frying" },
    { label: "sea" , value: "sea" },
    { label: "assorted" , value: "assorted" },
    { label: "goose" , value: "goose" },
    { label: "black" , value: "black" },
    { label: "matzo" , value: "matzo" },
    { label: "fat" , value: "fat" },
    { label: "dried" , value: "dried" },
    { label: "solid" , value: "solid" },
    { label: "amaretti" , value: "amaretti" },
    { label: "dried" , value: "dried" },
    { label: "hijiki" , value: "hijiki" },
    { label: "hard" , value: "hard" },
    { label: "masterpiece" , value: "masterpiece" },
    { label: "round" , value: "round" },
    { label: "chicken" , value: "chicken" },
    { label: "mexicorn" , value: "mexicorn" },
    { label: "instant" , value: "instant" },
    { label: "blueberry" , value: "blueberry" },
    { label: "unsweetened" , value: "unsweetened" },
    { label: "dry" , value: "dry" },
    { label: "fresh" , value: "fresh" },
    { label: "ground" , value: "ground" },
    { label: "peanut" , value: "peanut" },
    { label: "seedless" , value: "seedless" },
    { label: "pomegranate" , value: "pomegranate" },
    { label: "pirouette" , value: "pirouette" },
    { label: "dried" , value: "dried" },
    { label: "canned" , value: "canned" },
    { label: "cucuzza" , value: "cucuzza" },
    { label: "fromage" , value: "fromage" },
    { label: "maraschino" , value: "maraschino" },
    { label: "fat" , value: "fat" },
    { label: "mahlepi" , value: "mahlepi" },
    { label: "wheat" , value: "wheat" },
    { label: "sour" , value: "sour" },
    { label: "chicken" , value: "chicken" },
    { label: "aleppo" , value: "aleppo" },
    { label: "low-fat" , value: "low-fat" },
    { label: "pickled" , value: "pickled" },
    { label: "watercress" , value: "watercress" },
    { label: "country" , value: "country" },
    { label: "dry-roasted" , value: "dry-roasted" },
    { label: "cooked" , value: "cooked" },
    { label: "lean" , value: "lean" },
    { label: "six-pepper" , value: "six-pepper" },
    { label: "soda" , value: "soda" },
    { label: "refrigerated" , value: "refrigerated" },
    { label: "cheese" , value: "cheese" },
    { label: "cheddar" , value: "cheddar" },
    { label: "boneless" , value: "boneless" },
    { label: "miniature" , value: "miniature" },
    { label: "tostado" , value: "tostado" },
    { label: "bone-in" , value: "bone-in" },
    { label: "habanero" , value: "habanero" },
    { label: "cocoa" , value: "cocoa" },
    { label: "vegetable" , value: "vegetable" },
    { label: "vanilla" , value: "vanilla" },
    { label: "plain" , value: "plain" },
    { label: "carbonated" , value: "carbonated" },
    { label: "dried" , value: "dried" },
    { label: "seasoned" , value: "seasoned" },
    { label: "celery" , value: "celery" },
    { label: "thai" , value: "thai" },
    { label: "red" , value: "red" },
    { label: "mexican" , value: "mexican" },
    { label: "orange" , value: "orange" },
    { label: "cooked" , value: "cooked" },
    { label: "sweet" , value: "sweet" },
    { label: "naan" , value: "naan" },
    { label: "wesson" , value: "wesson" },
    { label: "low-fat" , value: "low-fat" },
    { label: "midori" , value: "midori" },
    { label: "instant" , value: "instant" },
    { label: "green" , value: "green" },
    { label: "dried" , value: "dried" },
    { label: "butterscotch" , value: "butterscotch" },
    { label: "leg" , value: "leg" },
    { label: "pitted" , value: "pitted" },
    { label: "chevre" , value: "chevre" },
    { label: "green" , value: "green" },
    { label: "bottled" , value: "bottled" },
    { label: "sweet" , value: "sweet" },
    { label: "chicken" , value: "chicken" },
    { label: "mixed" , value: "mixed" },
    { label: "cooked" , value: "cooked" },
    { label: "pomegranate" , value: "pomegranate" },
    { label: "mung" , value: "mung" },
    { label: "garlic" , value: "garlic" },
    { label: "small" , value: "small" },
    { label: "small" , value: "small" },
    { label: "venison" , value: "venison" },
    { label: "barley" , value: "barley" },
    { label: "tempura" , value: "tempura" },
    { label: "boneless" , value: "boneless" },
    { label: "dried" , value: "dried" },
    { label: "onion" , value: "onion" },
    { label: "soy" , value: "soy" },
    { label: "cotton" , value: "cotton" },
    { label: "cranberry" , value: "cranberry" },
    { label: "special" , value: "special" },
    { label: "coarse" , value: "coarse" },
    { label: "fresh" , value: "fresh" },
    { label: "capsicums" , value: "capsicums" },
    { label: "chocolate" , value: "chocolate" },
    { label: "low-fat" , value: "low-fat" },
    { label: "peppermint" , value: "peppermint" },
    { label: "frozen" , value: "frozen" },
    { label: "fresh" , value: "fresh" },
    { label: "baby" , value: "baby" },
    { label: "frozen" , value: "frozen" },
    { label: "pickled" , value: "pickled" },
    { label: "jar" , value: "jar" },
    { label: "lemon" , value: "lemon" },
    { label: "nopalitos" , value: "nopalitos" },
    { label: "lemon" , value: "lemon" },
    { label: "egg" , value: "egg" },
    { label: "ranch" , value: "ranch" },
    { label: "sambhar" , value: "sambhar" },
    { label: "white" , value: "white" },
    { label: "sea" , value: "sea" },
    { label: "lingonberry" , value: "lingonberry" },
    { label: "pork" , value: "pork" },
    { label: "crystallized" , value: "crystallized" },
    { label: "shellfish" , value: "shellfish" },
    { label: "extra" , value: "extra" },
    { label: "kelloggs" , value: "kelloggs" },
    { label: "chocolate" , value: "chocolate" },
    { label: "venison" , value: "venison" },
    { label: "martha" , value: "martha" },
    { label: "white" , value: "white" },
    { label: "quick" , value: "quick" },
    { label: "frozen" , value: "frozen" },
    { label: "mint-flavored" , value: "mint-flavored" },
    { label: "heads" , value: "heads" },
    { label: "chocolate" , value: "chocolate" },
    { label: "arbol" , value: "arbol" },
    { label: "vegan" , value: "vegan" },
    { label: "corn" , value: "corn" },
    { label: "gravox" , value: "gravox" },
    { label: "danish" , value: "danish" },
    { label: "liquid" , value: "liquid" },
    { label: "black" , value: "black" },
    { label: "crescent" , value: "crescent" },
    { label: "yellow" , value: "yellow" },
    { label: "fruit" , value: "fruit" },
    { label: "baked" , value: "baked" },
    { label: "candied" , value: "candied" },
    { label: "fresh" , value: "fresh" },
    { label: "rib" , value: "rib" },
    { label: "cinnamon" , value: "cinnamon" },
    { label: "ginger" , value: "ginger" },
    { label: "roasted" , value: "roasted" },
    { label: "crisco" , value: "crisco" },
    { label: "jalapeno" , value: "jalapeno" },
    { label: "sweetened" , value: "sweetened" },
    { label: "horseradish" , value: "horseradish" },
    { label: "round" , value: "round" },
    { label: "hot" , value: "hot" },
    { label: "low-fat" , value: "low-fat" },
    { label: "fat-free" , value: "fat-free" },
    { label: "sesame" , value: "sesame" },
    { label: "oil" , value: "oil" },
    { label: "nutmeg" , value: "nutmeg" },
    { label: "half-and-half" , value: "half-and-half" },
    { label: "pumpkin" , value: "pumpkin" },
    { label: "corn" , value: "corn" },
    { label: "white" , value: "white" },
    { label: "bananas" , value: "bananas" },
    { label: "pizza" , value: "pizza" },
    { label: "thai" , value: "thai" },
    { label: "root" , value: "root" },
    { label: "hazelnuts" , value: "hazelnuts" },
    { label: "green" , value: "green" },
    { label: "cooking" , value: "cooking" },
    { label: "fresh" , value: "fresh" },
    { label: "rutabagas" , value: "rutabagas" },
    { label: "port" , value: "port" },
    { label: "brown" , value: "brown" },
    { label: "absolut" , value: "absolut" },
    { label: "canned" , value: "canned" },
    { label: "boneless" , value: "boneless" },
    { label: "cheddar" , value: "cheddar" },
    { label: "instant" , value: "instant" },
    { label: "salt-free" , value: "salt-free" },
    { label: "beef" , value: "beef" },
    { label: "whole" , value: "whole" },
    { label: "reduced-calorie" , value: "reduced-calorie" },
    { label: "cornbread" , value: "cornbread" },
    { label: "hard" , value: "hard" },
    { label: "9-inch" , value: "9-inch" },
    { label: "sweet" , value: "sweet" },
    { label: "cortland" , value: "cortland" },
    { label: "9-inch" , value: "9-inch" },
    { label: "ritz" , value: "ritz" },
    { label: "asiago" , value: "asiago" },
    { label: "chile" , value: "chile" },
    { label: "bagels" , value: "bagels" },
    { label: "vegetable" , value: "vegetable" },
    { label: "grouper" , value: "grouper" },
    { label: "golden" , value: "golden" },
    { label: "mixed" , value: "mixed" },
    { label: "garlic" , value: "garlic" },
    { label: "miniature" , value: "miniature" },
    { label: "no-salt-added" , value: "no-salt-added" },
    { label: "shin" , value: "shin" },
    { label: "bermuda" , value: "bermuda" },
    { label: "frozen" , value: "frozen" },
    { label: "unbaked" , value: "unbaked" },
    { label: "peanut" , value: "peanut" },
    { label: "chili" , value: "chili" },
    { label: "biscuit" , value: "biscuit" },
    { label: "smoked" , value: "smoked" },
    { label: "unsweetened" , value: "unsweetened" },
    { label: "sea" , value: "sea" },
    { label: "mushroom" , value: "mushroom" },
    { label: "peanut" , value: "peanut" },
    { label: "chocolate" , value: "chocolate" },
    { label: "lipton" , value: "lipton" },
    { label: "frozen" , value: "frozen" },
    { label: "soul" , value: "soul" },
    { label: "lamb" , value: "lamb" },
    { label: "3-inch" , value: "3-inch" },
    { label: "sugar-free" , value: "sugar-free" },
    { label: "6-inch" , value: "6-inch" },
    { label: "orange" , value: "orange" },
    { label: "fat" , value: "fat" },
    { label: "reddi-wip" , value: "reddi-wip" },
    { label: "reduced-fat" , value: "reduced-fat" },
    { label: "turkey" , value: "turkey" },
    { label: "baby" , value: "baby" },
    { label: "worcestershire" , value: "worcestershire" },
    { label: "green" , value: "green" },
    { label: "orange" , value: "orange" },
    { label: "new" , value: "new" },
    { label: "better" , value: "better" },
    { label: "seedless" , value: "seedless" },
    { label: "sodium-free" , value: "sodium-free" },
    { label: "red" , value: "red" },
    { label: "cardamom" , value: "cardamom" },
    { label: "strawberry" , value: "strawberry" },
    { label: "doves" , value: "doves" },
    { label: "kraft" , value: "kraft" },
    { label: "hunts" , value: "hunts" },
    { label: "sauterne" , value: "sauterne" },
    { label: "wild" , value: "wild" },
    { label: "quaker" , value: "quaker" },
    { label: "fudge" , value: "fudge" },
    { label: "fish" , value: "fish" },
    { label: "pisco" , value: "pisco" },
    { label: "ti" , value: "ti" },
    { label: "corn" , value: "corn" },
    { label: "crystallized" , value: "crystallized" },
    { label: "fresh" , value: "fresh" },
    { label: "purple" , value: "purple" },
    { label: "low-salt" , value: "low-salt" },
    { label: "92%" , value: "92%" },
    { label: "red" , value: "red" },
    { label: "dry" , value: "dry" },
    { label: "dish" , value: "dish" },
    { label: "baby" , value: "baby" },
    { label: "burghul" , value: "burghul" },
    { label: "glazed" , value: "glazed" },
    { label: "hibiscus" , value: "hibiscus" },
    { label: "caffeine-free" , value: "caffeine-free" },
    { label: "whole" , value: "whole" },
    { label: "chi" , value: "chi" },
    { label: "fat-free" , value: "fat-free" },
    { label: "instant" , value: "instant" },
    { label: "chocolate" , value: "chocolate" },
    { label: "9-inch" , value: "9-inch" },
    { label: "sugar" , value: "sugar" },
    { label: "fresh" , value: "fresh" },
    { label: "english" , value: "english" },
    { label: "duncan" , value: "duncan" },
    { label: "vanilla" , value: "vanilla" },
    { label: "smuckers" , value: "smuckers" },
    { label: "havarti" , value: "havarti" },
    { label: "fresh" , value: "fresh" },
    { label: "de-fatted" , value: "de-fatted" },
    { label: "guinea" , value: "guinea" },
    { label: "unsweetened" , value: "unsweetened" },
    { label: "cooked" , value: "cooked" },
    { label: "strawberry" , value: "strawberry" },
    { label: "yak" , value: "yak" },
    { label: "cracked" , value: "cracked" },
    { label: "roasted" , value: "roasted" },
    { label: "sugar-free" , value: "sugar-free" },
    { label: "dry" , value: "dry" },
    { label: "light" , value: "light" },
    { label: "italian" , value: "italian" },
    { label: "apple" , value: "apple" },
    { label: "hash" , value: "hash" },
    { label: "baking" , value: "baking" },
    { label: "thin" , value: "thin" },
    { label: "cupcake" , value: "cupcake" },
    { label: "cumin" , value: "cumin" },
    { label: "mushrooms" , value: "mushrooms" },
    { label: "sun-dried" , value: "sun-dried" },
    { label: "hot" , value: "hot" },
    { label: "sardines" , value: "sardines" },
    { label: "pimento" , value: "pimento" },
    { label: "whole" , value: "whole" },
    { label: "vanilla" , value: "vanilla" },
    { label: "gem" , value: "gem" },
    { label: "mrs." , value: "mrs." },
    { label: "light-brown" , value: "light-brown" },
    { label: "sugar-free" , value: "sugar-free" },
    { label: "low-fat" , value: "low-fat" },
    { label: "corn" , value: "corn" },
    { label: "sea" , value: "sea" },
    { label: "fat" , value: "fat" },
    { label: "apple" , value: "apple" },
    { label: "deli" , value: "deli" },
    { label: "small" , value: "small" },
    { label: "cooked" , value: "cooked" },
    { label: "ground" , value: "ground" },
    { label: "fine" , value: "fine" },
    { label: "monterey" , value: "monterey" },
    { label: "cracker" , value: "cracker" },
    { label: "gingerroot" , value: "gingerroot" },
    { label: "hen" , value: "hen" },
    { label: "plastic" , value: "plastic" },
    { label: "peach" , value: "peach" },
    { label: "canned" , value: "canned" },
    { label: "italian" , value: "italian" },
    { label: "graham" , value: "graham" },
    { label: "lean" , value: "lean" },
    { label: "lean" , value: "lean" },
    { label: "baby" , value: "baby" },
    { label: "queso" , value: "queso" },
    { label: "spanish" , value: "spanish" },
    { label: "custard" , value: "custard" },
    { label: "italian-style" , value: "italian-style" },
    { label: "gold" , value: "gold" },
    { label: "andes" , value: "andes" },
    { label: "beets" , value: "beets" },
    { label: "baby" , value: "baby" },
    { label: "monterey" , value: "monterey" },
    { label: "mixed" , value: "mixed" },
    { label: "sweet" , value: "sweet" },
    { label: "white" , value: "white" },
    { label: "chile" , value: "chile" },
    { label: "shiitake" , value: "shiitake" },
    { label: "bonito" , value: "bonito" },
    { label: "laurel" , value: "laurel" },
    { label: "white" , value: "white" },
    { label: "olives" , value: "olives" },
    { label: "prune" , value: "prune" },
    { label: "white" , value: "white" },
    { label: "tubetti" , value: "tubetti" },
    { label: "pierogi" , value: "pierogi" },
    { label: "jiffy" , value: "jiffy" },
    { label: "m&ms" , value: "m&ms" },
    { label: "chicken" , value: "chicken" },
    { label: "hersheys" , value: "hersheys" },
    { label: "oscar" , value: "oscar" },
    { label: "crystal" , value: "crystal" },
    { label: "kelloggs" , value: "kelloggs" },
    { label: "non-fat" , value: "non-fat" },
    { label: "baking" , value: "baking" },
    { label: "breadsticks" , value: "breadsticks" },
    { label: "skinless" , value: "skinless" },
    { label: "honey" , value: "honey" },
    { label: "honey" , value: "honey" },
    { label: "sandwich" , value: "sandwich" },
    { label: "refrigerated" , value: "refrigerated" },
    { label: "dark" , value: "dark" },
    { label: "stolichnaya" , value: "stolichnaya" },
    { label: "cola-flavored" , value: "cola-flavored" },
    { label: "mushroom" , value: "mushroom" },
    { label: "cookie" , value: "cookie" },
    { label: "canned" , value: "canned" },
    { label: "planters" , value: "planters" },
    { label: "stuffed" , value: "stuffed" },
    { label: "sweet" , value: "sweet" },
    { label: "rajma" , value: "rajma" },
    { label: "candied" , value: "candied" },
    { label: "vegetable" , value: "vegetable" },
    { label: "burritos" , value: "burritos" },
    { label: "roast" , value: "roast" },
    { label: "yellowfin" , value: "yellowfin" },
    { label: "chile-infused" , value: "chile-infused" },
    { label: "candied" , value: "candied" },
    { label: "maggi" , value: "maggi" },
    { label: "sugar-free" , value: "sugar-free" },
    { label: "au" , value: "au" },
    { label: "rotis" , value: "rotis" },
    { label: "cocoa" , value: "cocoa" },
    { label: "tsubushi-an" , value: "tsubushi-an" },
    { label: "cranberry" , value: "cranberry" },
    { label: "smoked" , value: "smoked" },
    { label: "hawaiian" , value: "hawaiian" },
    { label: "yolk-free" , value: "yolk-free" },
    { label: "sweet" , value: "sweet" },
    { label: "french" , value: "french" },
    { label: "rock" , value: "rock" },
    { label: "strawberry" , value: "strawberry" },
    { label: "vanilla" , value: "vanilla" },
    { label: "caramel" , value: "caramel" },
    { label: "beef" , value: "beef" },
    { label: "pork" , value: "pork" },
    { label: "gai" , value: "gai" },
    { label: "semisweet" , value: "semisweet" },
    { label: "honey" , value: "honey" },
    { label: "non-dairy" , value: "non-dairy" },
    { label: "benefiber" , value: "benefiber" },
    { label: "canola" , value: "canola" },
    { label: "sweet" , value: "sweet" },
    { label: "fettuccine" , value: "fettuccine" },
    { label: "fresh" , value: "fresh" },
    { label: "albacore" , value: "albacore" },
    { label: "breadcrumbs" , value: "breadcrumbs" },
    { label: "budweiser" , value: "budweiser" },
    { label: "allspice" , value: "allspice" },
    { label: "brown" , value: "brown" },
    { label: "cold" , value: "cold" },
    { label: "smoked" , value: "smoked" },
    { label: "fenugreek" , value: "fenugreek" },
    { label: "boneless" , value: "boneless" },
    { label: "fat-free" , value: "fat-free" },
    { label: "italian" , value: "italian" },
    { label: "five-spice" , value: "five-spice" },
    { label: "hot" , value: "hot" },
    { label: "fine" , value: "fine" },
    { label: "aluminum" , value: "aluminum" },
    { label: "peppercorn" , value: "peppercorn" },
    { label: "potato" , value: "potato" },
    { label: "lean" , value: "lean" },
    { label: "gin" , value: "gin" },
    { label: "basa" , value: "basa" },
    { label: "fat-free" , value: "fat-free" },
    { label: "hard" , value: "hard" },
    { label: "herb" , value: "herb" },
    { label: "amish" , value: "amish" },
    { label: "vegemite" , value: "vegemite" },
    { label: "white" , value: "white" },
    { label: "sweet" , value: "sweet" },
    { label: "low-sodium" , value: "low-sodium" },
    { label: "romaine" , value: "romaine" },
    { label: "unsifted" , value: "unsifted" },
    { label: "lean" , value: "lean" },
    { label: "sparerib" , value: "sparerib" },
    { label: "crisp" , value: "crisp" },
    { label: "boston" , value: "boston" },
    { label: "kaiser" , value: "kaiser" },
    { label: "frozen" , value: "frozen" },
    { label: "reduced-fat" , value: "reduced-fat" },
    { label: "sugar-free" , value: "sugar-free" },
    { label: "pizza" , value: "pizza" },
    { label: "swordfish" , value: "swordfish" },
    { label: "banana" , value: "banana" },
    { label: "swiss" , value: "swiss" },
    { label: "kumara" , value: "kumara" },
    { label: "chocolate" , value: "chocolate" },
    { label: "red" , value: "red" },
    { label: "dry-roasted" , value: "dry-roasted" },
    { label: "corn" , value: "corn" },
    { label: "mild" , value: "mild" },
    { label: "chili" , value: "chili" },
    { label: "zatarains" , value: "zatarains" },
    { label: "beef" , value: "beef" },
    { label: "brickle" , value: "brickle" },
    { label: "black" , value: "black" },
    { label: "blueberry-flavored" , value: "blueberry-flavored" },
    { label: "pomegranate-blueberry" , value: "pomegranate-blueberry" },
    { label: "reduced-fat" , value: "reduced-fat" },
    { label: "hazelnut-flavored" , value: "hazelnut-flavored" },
    { label: "vanilla" , value: "vanilla" },
    { label: "porcini" , value: "porcini" },
    { label: "pineapple" , value: "pineapple" },
    { label: "three-cheese" , value: "three-cheese" },
    { label: "hoagie" , value: "hoagie" },
    { label: "reduced-fat" , value: "reduced-fat" },
    { label: "grape" , value: "grape" },
    { label: "cream" , value: "cream" },
    { label: "red" , value: "red" },
    { label: "tamales" , value: "tamales" },
    { label: "cinnamon-raisin" , value: "cinnamon-raisin" },
    { label: "rose" , value: "rose" },
    { label: "mint" , value: "mint" },
    { label: "reduced" , value: "reduced" },
    { label: "jalapeno" , value: "jalapeno" },
    { label: "seedless" , value: "seedless" },
    { label: "live" , value: "live" },
    { label: "skinless" , value: "skinless" },
    { label: "oyster" , value: "oyster" },
    { label: "durkee" , value: "durkee" },
    { label: "goat" , value: "goat" },
    { label: "good" , value: "good" },
    { label: "sugar" , value: "sugar" },
  ]

optionsTags  = [
    {label: "valentines-day" , value: "valentines-day" },
    {label: "bear" , value: "bear" },
    {label: "side-dish" , value: "side-dish" },
    {label: "beans" , value: "beans" },
    {label: "frosting" , value: "frosting" },
    {label: "gluten-free" , value: "gluten-free" },
    {label: "from-scratch" , value: "from-scratch" },
    {label: "micro-melanesia" , value: "micro-melanesia" },
    {label: "valentines-day" , value: "valentines-day" },
    {label: "appetizer" , value: "appetizer" },
    {label: "greens" , value: "greens" },
    {label: "meat" , value: "meat" },
    {label: "diabetic" , value: "diabetic" },
    {label: "lactose" , value: "lactose" },
    {label: "spreads" , value: "spreads" },
    {label: "marinades" , value: "marinades" },
    {label: "thanksgiving" , value: "thanksgiving" },
    {label: "swedish" , value: "swedish" },
    {label: "ethiopian" , value: "ethiopian" },
    {label: "puerto-rican" , value: "puerto-rican" },
    {label: "no-cook" , value: "no-cook" },
    {label: "black-beans" , value: "black-beans" },
    {label: "yeast" , value: "yeast" },
    {label: "sauces" , value: "sauces" },
    {label: "barley" , value: "barley" },
    {label: "barbecue" , value: "barbecue" },
    {label: "marinara-sauce" , value: "marinara-sauce" },
    {label: "barbecue" , value: "barbecue" },
    {label: "venezuelan" , value: "venezuelan" },
    {label: "greek" , value: "greek" },
    {label: "chicken-thighs-legs" , value: "chicken-thighs-legs" },
    {label: "sauce" , value: "sauce" },
    {label: "sweet-potatoes" , value: "sweet-potatoes" },
    {label: "turkish" , value: "turkish" },
    {label: "octopus" , value: "octopus" },
    {label: "marinades" , value: "marinades" },
    {label: "gelatin" , value: "gelatin" },
    {label: "artichoke" , value: "artichoke" },
    {label: "welsh" , value: "welsh" },
    {label: "perch" , value: "perch" },
    {label: "food-processor" , value: "food-processor" },
    {label: "dehydrated" , value: "dehydrated" },
    {label: "melons" , value: "melons" },
    {label: "muffins" , value: "muffins" },
    {label: "low-protein" , value: "low-protein" },
    {label: "bass" , value: "bass" },
    {label: "palestinian" , value: "palestinian" },
    {label: "rolled-cookies" , value: "rolled-cookies" },
    {label: "biscotti" , value: "biscotti" },
    {label: "medium-grain-rice" , value: "medium-grain-rice" },
    {label: "broccoli" , value: "broccoli" },
    {label: "winter" , value: "winter" },
    {label: "northeastern-united-states" , value: "northeastern-united-states" },
    {label: "low-saturated-fat" , value: "low-saturated-fat" },
    {label: "cheesecake" , value: "cheesecake" },
    {label: "shellfish" , value: "shellfish" },
    {label: "shellfish" , value: "shellfish" },
    {label: "sourdough" , value: "sourdough" },
    {label: "cherries" , value: "cherries" },
    {label: "deer" , value: "deer" },
    {label: "mothers-day" , value: "mothers-day" },
    {label: "smoothies" , value: "smoothies" },
    {label: "roast" , value: "roast" },
    {label: "sudanese" , value: "sudanese" },
    {label: "eggs" , value: "eggs" },
    {label: "baking" , value: "baking" },
    {label: "ravioli-tortellini" , value: "ravioli-tortellini" },
    {label: "ecuadorean" , value: "ecuadorean" },
    {label: "native-american" , value: "native-american" },
    {label: "pancakes" , value: "pancakes" },
    {label: "oaxacan" , value: "oaxacan" },
    {label: "white-rice" , value: "white-rice" },
    {label: "quiche" , value: "quiche" },
    {label: "spanish" , value: "spanish" },
    {label: "pot-pie" , value: "pot-pie" },
    {label: "potatoes" , value: "potatoes" },
    {label: "rosh-hashana" , value: "rosh-hashana" },
    {label: "oamc" , value: "oamc" },
    {label: "californian" , value: "californian" },
    {label: "spinach" , value: "spinach" },
    {label: "cookies" , value: "cookies" },
    {label: "pacific-northwest" , value: "pacific-northwest" },
    {label: "cheap" , value: "cheap" },
    {label: "broil" , value: "broil" },
    {label: "pressure-cooker" , value: "pressure-cooker" },
    {label: "scottish" , value: "scottish" },
    {label: "main-dish" , value: "main-dish" },
    {label: "main-dish" , value: "main-dish" },
    {label: "turkey" , value: "turkey" },
    {label: "new-zealand" , value: "new-zealand" },
    {label: "chili" , value: "chili" },
    {label: "halloween" , value: "halloween" },
    {label: "side-dish" , value: "side-dish" },
    {label: "5-ingredients-or-less" , value: "5-ingredients-or-less" },
    {label: "low-protein" , value: "low-protein" },
    {label: "mixer" , value: "mixer" },
    {label: "hidden-valley-ranch" , value: "hidden-valley-ranch" },
    {label: "halibut" , value: "halibut" },
    {label: "super-bowl" , value: "super-bowl" },
    {label: "bread" , value: "bread" },
    {label: "pizza" , value: "pizza" },
    {label: "georgian" , value: "georgian" },
    {label: "black-beans" , value: "black-beans" },
    {label: "30-minutes-or-less" , value: "30-minutes-or-less" },
    {label: "cheesecake" , value: "cheesecake" },
    {label: "egyptian" , value: "egyptian" },
    {label: "spanish" , value: "spanish" },
    {label: "flounder" , value: "flounder" },
    {label: "one-dish-meal" , value: "one-dish-meal" },
    {label: "central-american" , value: "central-american" },
    {label: "4-hours-or-less" , value: "4-hours-or-less" },
    {label: "yams" , value: "yams" },
    {label: "hungarian" , value: "hungarian" },
    {label: "chowders" , value: "chowders" },
    {label: "whole-duck" , value: "whole-duck" },
    {label: "hanukkah" , value: "hanukkah" },
    {label: "honduran" , value: "honduran" },
    {label: "pressure-canning" , value: "pressure-canning" },
    {label: "chilean" , value: "chilean" },
    {label: "summer" , value: "summer" },
    {label: "medium-grain-rice" , value: "medium-grain-rice" },
    {label: "thanksgiving" , value: "thanksgiving" },
    {label: "clear-soup" , value: "clear-soup" },
    {label: "chinese-new-year" , value: "chinese-new-year" },
    {label: "desserts" , value: "desserts" },
    {label: "cinco-de-mayo" , value: "cinco-de-mayo" },
    {label: "jams-and-preserves" , value: "jams-and-preserves" },
    {label: "american" , value: "american" },
    {label: "pork-loin" , value: "pork-loin" },
    {label: "gluten-free" , value: "gluten-free" },
    {label: "high-protein" , value: "high-protein" },
    {label: "beverage" , value: "beverage" },
    {label: "hand-formed-cookies" , value: "hand-formed-cookies" },
    {label: "spaghetti" , value: "spaghetti" },
    {label: "scones" , value: "scones" },
    {label: "rolls" , value: "rolls" },
    {label: "appetizer" , value: "appetizer" },
    {label: "mixer" , value: "mixer" },
    {label: "sole" , value: "sole" },
    {label: "served-cold" , value: "served-cold" },
    {label: "seasonal" , value: "seasonal" },
    {label: "short-grain-rice" , value: "short-grain-rice" },
    {label: "brazilian" , value: "brazilian" },
    {label: "chocolate-chip-cookies" , value: "chocolate-chip-cookies" },
    {label: "peruvian" , value: "peruvian" },
    {label: "crock-pot" , value: "crock-pot" },
    {label: "palestinian" , value: "palestinian" },
    {label: "duck" , value: "duck" },
    {label: "gumbo" , value: "gumbo" },
    {label: "lettuces" , value: "lettuces" },
    {label: "scandinavian" , value: "scandinavian" },
    {label: "beverage" , value: "beverage" },
    {label: "for-large-groups" , value: "for-large-groups" },
    {label: "mushrooms" , value: "mushrooms" },
    {label: "citrus" , value: "citrus" },
    {label: "sandwiches" , value: "sandwiches" },
    {label: "1-day-or-more" , value: "1-day-or-more" },
    {label: "finger-food" , value: "finger-food" },
    {label: "vegetables" , value: "vegetables" },
    {label: "spicy" , value: "spicy" },
    {label: "clams" , value: "clams" },
    {label: "tempeh" , value: "tempeh" },
    {label: "microwave" , value: "microwave" },
    {label: "cauliflower" , value: "cauliflower" },
    {label: "a1-sauce" , value: "a1-sauce" },
    {label: "bananas" , value: "bananas" },
    {label: "kosher" , value: "kosher" },
    {label: "easter" , value: "easter" },
    {label: "soy" , value: "soy" },
    {label: "soy-tofu" , value: "soy-tofu" },
    {label: "rabbit" , value: "rabbit" },
    {label: "orange-roughy" , value: "orange-roughy" },
    {label: "dinner-party" , value: "dinner-party" },
    {label: "beginner" , value: "beginner" },
    {label: "tilapia" , value: "tilapia" },
    {label: "colombian" , value: "colombian" },
    {label: "cupcakes" , value: "cupcakes" },
    {label: "spicy" , value: "spicy" },
    {label: "chili" , value: "chili" },
    {label: "dinner-party" , value: "dinner-party" },
    {label: "austrian" , value: "austrian" },
    {label: "short-grain-rice" , value: "short-grain-rice" },
    {label: "chicken" , value: "chicken" },
    {label: "tomatoes" , value: "tomatoes" },
    {label: "peanut-butter" , value: "peanut-butter" },
    {label: "pressure-cooker" , value: "pressure-cooker" },
    {label: "middle-eastern" , value: "middle-eastern" },
    {label: "sweet-sauces" , value: "sweet-sauces" },
    {label: "healthy" , value: "healthy" },
    {label: "papaya" , value: "papaya" },
    {label: "peppers" , value: "peppers" },
    {label: "peaches" , value: "peaches" },
    {label: "toddler-friendly" , value: "toddler-friendly" },
    {label: "chinese" , value: "chinese" },
    {label: "grapes" , value: "grapes" },
    {label: "christmas" , value: "christmas" },
    {label: "cheese" , value: "cheese" },
    {label: "shakes" , value: "shakes" },
    {label: "cuban" , value: "cuban" },
    {label: "easy" , value: "easy" },
    {label: "gumbo" , value: "gumbo" },
    {label: "slow-cooker" , value: "slow-cooker" },
    {label: "oranges" , value: "oranges" },
    {label: "somalian" , value: "somalian" },
    {label: "sweet" , value: "sweet" },
    {label: "roast" , value: "roast" },
    {label: "tofu" , value: "tofu" },
    {label: "easy" , value: "easy" },
    {label: "congolese" , value: "congolese" },
    {label: "high-protein" , value: "high-protein" },
    {label: "condiments" , value: "condiments" },
    {label: "low-calorie" , value: "low-calorie" },
    {label: "asian" , value: "asian" },
    {label: "guatemalan" , value: "guatemalan" },
    {label: "meatballs" , value: "meatballs" },
    {label: "waffles" , value: "waffles" },
    {label: "indonesian" , value: "indonesian" },
    {label: "tex-mex" , value: "tex-mex" },
    {label: "grains" , value: "grains" },
    {label: "german" , value: "german" },
    {label: "pheasant" , value: "pheasant" },
    {label: "baja" , value: "baja" },
    {label: "scones" , value: "scones" },
    {label: "jams-and-preserves" , value: "jams-and-preserves" },
    {label: "soul" , value: "soul" },
    {label: "mussels" , value: "mussels" },
    {label: "australian" , value: "australian" },
    {label: "herbs-and-spice-mix" , value: "herbs-and-spice-mix" },
    {label: "vegan" , value: "vegan" },
    {label: "high-calcium" , value: "high-calcium" },
    {label: "comfort-food" , value: "comfort-food" },
    {label: "hungarian" , value: "hungarian" },
    {label: "czech" , value: "czech" },
    {label: "iranian" , value: "iranian" },
    {label: "pork-ribs" , value: "pork-ribs" },
    {label: "spaghetti" , value: "spaghetti" },
    {label: "oranges" , value: "oranges" },
    {label: "avocado" , value: "avocado" },
    {label: "stuffings-dressings" , value: "stuffings-dressings" },
    {label: "30-minutes-or-less" , value: "30-minutes-or-less" },
    {label: "whitefish" , value: "whitefish" },
    {label: "quail" , value: "quail" },
    {label: "cocktails" , value: "cocktails" },
    {label: "danish" , value: "danish" },
    {label: "creole" , value: "creole" },
    {label: "cod" , value: "cod" },
    {label: "cantonese" , value: "cantonese" },
    {label: "dips" , value: "dips" },
    {label: "pasta" , value: "pasta" },
    {label: "mardi-gras-carnival" , value: "mardi-gras-carnival" },
    {label: "snacks" , value: "snacks" },
    {label: "yams" , value: "yams" },
    {label: "fathers-day" , value: "fathers-day" },
    {label: "nepalese" , value: "nepalese" },
    {label: "pitted-fruit" , value: "pitted-fruit" },
    {label: "long-grain-rice" , value: "long-grain-rice" },
    {label: "1-day-or-more" , value: "1-day-or-more" },
    {label: "brazilian" , value: "brazilian" },
    {label: "beef" , value: "beef" },
    {label: "savory" , value: "savory" },
    {label: "iranian" , value: "iranian" },
    {label: "cupcakes" , value: "cupcakes" },
    {label: "kiwi" , value: "kiwi" },
    {label: "oatmeal" , value: "oatmeal" },
    {label: "sole" , value: "sole" },
    {label: "costa-rican" , value: "costa-rican" },
    {label: "clear-soup" , value: "clear-soup" },
    {label: "mongolian" , value: "mongolian" },
    {label: "guatemalan" , value: "guatemalan" },
    {label: "french" , value: "french" },
    {label: "freshwater-fish" , value: "freshwater-fish" },
    {label: "oysters" , value: "oysters" },
    {label: "honduran" , value: "honduran" },
    {label: "shrimp" , value: "shrimp" },
    {label: "lasagna" , value: "lasagna" },
    {label: "collard-greens" , value: "collard-greens" },
    {label: "saudi-arabian" , value: "saudi-arabian" },
    {label: "from-scratch" , value: "from-scratch" },
    {label: "chilean" , value: "chilean" },
    {label: "grains" , value: "grains" },
    {label: "pasta-shells" , value: "pasta-shells" },
    {label: "camping" , value: "camping" },
    {label: "romantic" , value: "romantic" },
    {label: "cooking-mixes" , value: "cooking-mixes" },
    {label: "fish" , value: "fish" },
    {label: "malaysian" , value: "malaysian" },
    {label: "pork" , value: "pork" },
    {label: "cod" , value: "cod" },
    {label: "swiss" , value: "swiss" },
    {label: "puddings" , value: "puddings" },
    {label: "mothers-day" , value: "mothers-day" },
    {label: "north-american" , value: "north-american" },
    {label: "sauces" , value: "sauces" },
    {label: "crawfish" , value: "crawfish" },
    {label: "plums" , value: "plums" },
    {label: "polynesian" , value: "polynesian" },
    {label: "pickeral" , value: "pickeral" },
    {label: "lunch" , value: "lunch" },
    {label: "halibut" , value: "halibut" },
    {label: "college" , value: "college" },
    {label: "green-yellow-beans" , value: "green-yellow-beans" },
    {label: "egyptian" , value: "egyptian" },
    {label: "southern-united-states" , value: "southern-united-states" },
    {label: "manicotti" , value: "manicotti" },
    {label: "korean" , value: "korean" },
    {label: "russian" , value: "russian" },
    {label: "south-west-pacific" , value: "south-west-pacific" },
    {label: "cherries" , value: "cherries" },
    {label: "catfish" , value: "catfish" },
    {label: "cranberry-sauce" , value: "cranberry-sauce" },
    {label: "pennsylvania-dutch" , value: "pennsylvania-dutch" },
    {label: "3-steps-or-less" , value: "3-steps-or-less" },
    {label: "high-fiber" , value: "high-fiber" },
    {label: "low-sodium" , value: "low-sodium" },
    {label: "camping" , value: "camping" },
    {label: "eggs" , value: "eggs" },
    {label: "cajun" , value: "cajun" },
    {label: "lime" , value: "lime" },
    {label: "ham" , value: "ham" },
    {label: "strawberries" , value: "strawberries" },
    {label: "moroccan" , value: "moroccan" },
    {label: "chutneys" , value: "chutneys" },
    {label: "brunch" , value: "brunch" },
    {label: "to-go" , value: "to-go" },
    {label: "cobblers-and-crisps" , value: "cobblers-and-crisps" },
    {label: "iraqi" , value: "iraqi" },
    {label: "grilling" , value: "grilling" },
    {label: "libyan" , value: "libyan" },
    {label: "bread" , value: "bread" },
    {label: "4-hours-or-less" , value: "4-hours-or-less" },
    {label: "pies" , value: "pies" },
    {label: "australian" , value: "australian" },
    {label: "berries" , value: "berries" },
    {label: "soups" , value: "soups" },
    {label: "crawfish" , value: "crawfish" },
    {label: "poultry" , value: "poultry" },
    {label: "mexican" , value: "mexican" },
    {label: "oamc" , value: "oamc" },
    {label: "coffee-cakes" , value: "coffee-cakes" },
    {label: "steam" , value: "steam" },
    {label: "bar-cookies" , value: "bar-cookies" },
    {label: "yeast" , value: "yeast" },
    {label: "elbow-macaroni" , value: "elbow-macaroni" },
    {label: "garnishes" , value: "garnishes" },
    {label: "polish" , value: "polish" },
    {label: "st-patricks-day" , value: "st-patricks-day" },
    {label: "icelandic" , value: "icelandic" },
    {label: "grilling" , value: "grilling" },
    {label: "porridge" , value: "porridge" },
    {label: "punch" , value: "punch" },
    {label: "salad-dressing" , value: "salad-dressing" },
    {label: "pork-sausage" , value: "pork-sausage" },
    {label: "mango" , value: "mango" },
    {label: "rolled-cookies" , value: "rolled-cookies" },
    {label: "fudge" , value: "fudge" },
    {label: "coconut" , value: "coconut" },
    {label: "memorial-day" , value: "memorial-day" },
    {label: "finger-food" , value: "finger-food" },
    {label: "april-fools-day" , value: "april-fools-day" },
    {label: "rabbit" , value: "rabbit" },
    {label: "wings" , value: "wings" },
    {label: "broil" , value: "broil" },
    {label: "lamb-sheep" , value: "lamb-sheep" },
    {label: "colombian" , value: "colombian" },
    {label: "saltwater-fish" , value: "saltwater-fish" },
    {label: "coconut" , value: "coconut" },
    {label: "crab" , value: "crab" },
    {label: "veal" , value: "veal" },
    {label: "stuffings-dressings" , value: "stuffings-dressings" },
    {label: "cocktails" , value: "cocktails" },
    {label: "angolan" , value: "angolan" },
    {label: "pork" , value: "pork" },
    {label: "leftovers" , value: "leftovers" },
    {label: "oven" , value: "oven" },
    {label: "wedding" , value: "wedding" },
    {label: "ravioli-tortellini" , value: "ravioli-tortellini" },
    {label: "czech" , value: "czech" },
    {label: "polynesian" , value: "polynesian" },
    {label: "lamb" , value: "lamb" },
    {label: "midwestern" , value: "midwestern" },
    {label: "wedding" , value: "wedding" },
    {label: "kid-friendly" , value: "kid-friendly" },
    {label: "canning" , value: "canning" },
    {label: "beef-sausage" , value: "beef-sausage" },
    {label: "beef-liver" , value: "beef-liver" },
    {label: "stove-top" , value: "stove-top" },
    {label: "healthy" , value: "healthy" },
    {label: "thai" , value: "thai" },
    {label: "vegetables" , value: "vegetables" },
    {label: "burgers" , value: "burgers" },
    {label: "college" , value: "college" },
    {label: "chocolate" , value: "chocolate" },
    {label: "seafood" , value: "seafood" },
    {label: "puddings" , value: "puddings" },
    {label: "trout" , value: "trout" },
    {label: "low-sodium" , value: "low-sodium" },
    {label: "tuna" , value: "tuna" },
    {label: "pitted-fruit" , value: "pitted-fruit" },
    {label: "english" , value: "english" },
    {label: "berries" , value: "berries" },
    {label: "mashed-potatoes" , value: "mashed-potatoes" },
    {label: "scottish" , value: "scottish" },
    {label: "pakistani" , value: "pakistani" },
    {label: "apples" , value: "apples" },
    {label: "lemon" , value: "lemon" },
    {label: "north-american" , value: "north-american" },
    {label: "corn" , value: "corn" },
    {label: "15-minutes-or-less" , value: "15-minutes-or-less" },
    {label: "romantic" , value: "romantic" },
    {label: "turkey" , value: "turkey" },
    {label: "hunan" , value: "hunan" },
    {label: "irish" , value: "irish" },
    {label: "chutneys" , value: "chutneys" },
    {label: "catfish" , value: "catfish" },
    {label: "filipino" , value: "filipino" },
    {label: "italian" , value: "italian" },
    {label: "green-yellow-beans" , value: "green-yellow-beans" },
    {label: "spring" , value: "spring" },
    {label: "grapes" , value: "grapes" },
    {label: "breakfast" , value: "breakfast" },
    {label: "deer" , value: "deer" },
    {label: "pot-pie" , value: "pot-pie" },
    {label: "side-dishes" , value: "side-dishes" },
    {label: "baked-beans" , value: "baked-beans" },
    {label: "cobblers-and-crisps" , value: "cobblers-and-crisps" },
    {label: "finnish" , value: "finnish" },
    {label: "caribbean" , value: "caribbean" },
    {label: "winter" , value: "winter" },
    {label: "ribs" , value: "ribs" },
    {label: "crab" , value: "crab" },
    {label: "stir-fry" , value: "stir-fry" },
    {label: "low-calorie" , value: "low-calorie" },
    {label: "american" , value: "american" },
    {label: "new-years" , value: "new-years" },
    {label: "whole-chicken" , value: "whole-chicken" },
    {label: "st-patricks-day" , value: "st-patricks-day" },
    {label: "sweet" , value: "sweet" },
    {label: "pears" , value: "pears" },
    {label: "infant-baby-friendly" , value: "infant-baby-friendly" },
    {label: "for-1-or-2" , value: "for-1-or-2" },
    {label: "fall" , value: "fall" },
    {label: "penne" , value: "penne" },
    {label: "vegan" , value: "vegan" },
    {label: "easter" , value: "easter" },
    {label: "kwanzaa" , value: "kwanzaa" },
    {label: "seasonal" , value: "seasonal" },
    {label: "spring" , value: "spring" },
    {label: "soups" , value: "soups" },
    {label: "midwestern" , value: "midwestern" },
    {label: "bananas" , value: "bananas" },
    {label: "potluck" , value: "potluck" },
    {label: "cream-soup" , value: "cream-soup" },
    {label: "low-carb" , value: "low-carb" },
    {label: "portuguese" , value: "portuguese" },
    {label: "keto" , value: "keto" },
    {label: "moroccan" , value: "moroccan" },
    {label: "meatloaf" , value: "meatloaf" },
    {label: "northeastern-united-states" , value: "northeastern-united-states" },
    {label: "blender" , value: "blender" },
    {label: "roast-beef" , value: "roast-beef" },
    {label: "mahi-mahi" , value: "mahi-mahi" },
    {label: "libyan" , value: "libyan" },
    {label: "eggplant" , value: "eggplant" },
    {label: "rice" , value: "rice" },
    {label: "onions" , value: "onions" },
    {label: "cooking-mixes" , value: "cooking-mixes" },
    {label: "pears" , value: "pears" },
    {label: "artichoke" , value: "artichoke" },
    {label: "low-cholesterol" , value: "low-cholesterol" },
    {label: "labor-day" , value: "labor-day" },
    {label: "lobster" , value: "lobster" },
    {label: "portuguese" , value: "portuguese" },
    {label: "picnic" , value: "picnic" },
    {label: "pork-chops" , value: "pork-chops" },
    {label: "stews" , value: "stews" },
    {label: "5-ingredients-or-less" , value: "5-ingredients-or-less" },
    {label: "low-fat" , value: "low-fat" },
    {label: "cookies" , value: "cookies" },
    {label: "bacon" , value: "bacon" },
    {label: "ramadan" , value: "ramadan" },
    {label: "squid" , value: "squid" },
    {label: "mashed-potatoes" , value: "mashed-potatoes" },
    {label: "norwegian" , value: "norwegian" },
    {label: "wings" , value: "wings" },
    {label: "beef-ribs" , value: "beef-ribs" },
    {label: "pudding" , value: "pudding" },
    {label: "peanut-butter" , value: "peanut-butter" },
    {label: "fruit" , value: "fruit" },
    {label: "asian" , value: "asian" },
    {label: "zucchini" , value: "zucchini" },
    {label: "raspberries" , value: "raspberries" },
    {label: "garnishes" , value: "garnishes" },
    {label: "chard" , value: "chard" },
    {label: "served-hot" , value: "served-hot" },
    {label: "peaches" , value: "peaches" },
    {label: "salmon" , value: "salmon" },
    {label: "pot-roast" , value: "pot-roast" },
    {label: "fruit" , value: "fruit" },
    {label: "cabbage" , value: "cabbage" },
    {label: "salad" , value: "salad" },
    {label: "seafood" , value: "seafood" },
    {label: "apples" , value: "apples" },
    {label: "indian" , value: "indian" },
    {label: "low-carb" , value: "low-carb" },
    {label: "freshwater-fish" , value: "freshwater-fish" },
    {label: "frozen-desserts" , value: "frozen-desserts" },
    {label: "granola" , value: "granola" },
    {label: "3-steps-or-less" , value: "3-steps-or-less" },
    {label: "brunch" , value: "brunch" },
    {label: "lasagna" , value: "lasagna" },
    {label: "brown-rice" , value: "brown-rice" },
    {label: "cambodian" , value: "cambodian" },
    {label: "chard" , value: "chard" },
    {label: "tomatoes" , value: "tomatoes" },
    {label: "english" , value: "english" },
    {label: "stir-fry" , value: "stir-fry" },
    {label: "african" , value: "african" },
    {label: "no-cook" , value: "no-cook" },
    {label: "peruvian" , value: "peruvian" },
    {label: "beginner" , value: "beginner" },
    {label: "beans" , value: "beans" },
    {label: "whole-turkey" , value: "whole-turkey" },
    {label: "middle-eastern" , value: "middle-eastern" },
    {label: "chick-peas-garbanzos" , value: "chick-peas-garbanzos" },
    {label: "indian" , value: "indian" },
    {label: "candy" , value: "candy" },
    {label: "to-go" , value: "to-go" },
    {label: "for-large-groups" , value: "for-large-groups" },
    {label: "amish-mennonite" , value: "amish-mennonite" },
    {label: "saltwater-fish" , value: "saltwater-fish" },
    {label: "polish" , value: "polish" },
    {label: "collard-greens" , value: "collard-greens" },
    {label: "breakfast" , value: "breakfast" },
    {label: "low-fat" , value: "low-fat" },
    {label: "argentine" , value: "argentine" },
    {label: "super-bowl" , value: "super-bowl" },
    {label: "drop-cookies" , value: "drop-cookies" },
    {label: "beef-kidney" , value: "beef-kidney" },
    {label: "south-american" , value: "south-american" },
    {label: "fudge" , value: "fudge" },
    {label: "lentils" , value: "lentils" },
    {label: "mango" , value: "mango" },
    {label: "stew" , value: "stew" },
    {label: "salads" , value: "salads" },
    {label: "cheese" , value: "cheese" },
    {label: "pasta" , value: "pasta" },
    {label: "mousses" , value: "mousses" },
    {label: "mushrooms" , value: "mushrooms" },
    {label: "low-cholesterol" , value: "low-cholesterol" },
    {label: "melons" , value: "melons" },
    {label: "mahi-mahi" , value: "mahi-mahi" },
    {label: "central-american" , value: "central-american" },
    {label: "casserole" , value: "casserole" },
    {label: "ground-beef" , value: "ground-beef" },
    {label: "african" , value: "african" },
    {label: "beef-liver" , value: "beef-liver" },
    {label: "canadian" , value: "canadian" },
    {label: "pacific-northwest" , value: "pacific-northwest" },
    {label: "served-hot" , value: "served-hot" },
    {label: "potatoes" , value: "potatoes" },
    {label: "pies" , value: "pies" },
    {label: "south-west-pacific" , value: "south-west-pacific" },
    {label: "hidden-valley-ranch" , value: "hidden-valley-ranch" },
    {label: "nuts" , value: "nuts" },
    {label: "rubs" , value: "rubs" },
    {label: "nigerian" , value: "nigerian" },
    {label: "cinco-de-mayo" , value: "cinco-de-mayo" },
    {label: "belgian" , value: "belgian" },
    {label: "brewing" , value: "brewing" },
    {label: "papaya" , value: "papaya" },
    {label: "hawaiian" , value: "hawaiian" },
    {label: "pastry-dough" , value: "pastry-dough" },
    {label: "high-fiber" , value: "high-fiber" },
    {label: "mussels" , value: "mussels" },
    {label: "blueberries" , value: "blueberries" },
    {label: "dessert" , value: "dessert" },
    {label: "served-cold" , value: "served-cold" },
    {label: "christmas" , value: "christmas" },
    {label: "fall" , value: "fall" },
    {label: "vegetarian" , value: "vegetarian" },
    {label: "soup" , value: "soup" },
    {label: "elk" , value: "elk" },
    {label: "moose" , value: "moose" },
    {label: "salmon" , value: "salmon" },
    {label: "coffee-cakes" , value: "coffee-cakes" },
    {label: "vietnamese" , value: "vietnamese" },
    {label: "wild-game" , value: "wild-game" },
    {label: "dairy" , value: "dairy" },
    {label: "cakes" , value: "cakes" },
    {label: "southwestern-united-states" , value: "southwestern-united-states" },
    {label: "sandwiches" , value: "sandwiches" },
    {label: "duck" , value: "duck" },
    {label: "mardi-gras-carnival" , value: "mardi-gras-carnival" },
    {label: "new-years" , value: "new-years" },
    {label: "macaroni-and-cheese" , value: "macaroni-and-cheese" },
    {label: "omelets-and-frittatas" , value: "omelets-and-frittatas" },
    {label: "russian" , value: "russian" },
    {label: "chocolate" , value: "chocolate" },
    {label: "canadian" , value: "canadian" },
    {label: "60-minutes-or-less" , value: "60-minutes-or-less" },
    {label: "one-dish-meal" , value: "one-dish-meal" },
    {label: "dips" , value: "dips" },
    {label: "diabetic" , value: "diabetic" },
    {label: "lime" , value: "lime" },
    {label: "italian" , value: "italian" },
    {label: "kid-friendly" , value: "kid-friendly" },
    {label: "south-american" , value: "south-american" },
    {label: "scandinavian" , value: "scandinavian" },
    {label: "squash" , value: "squash" },
    {label: "muffins" , value: "muffins" },
    {label: "cakes" , value: "cakes" },
    {label: "bisque" , value: "bisque" },
    {label: "lebanese" , value: "lebanese" },
    {label: "high-calcium" , value: "high-calcium" },
    {label: "icelandic" , value: "icelandic" },
    {label: "lunch" , value: "lunch" },
    {label: "comfort-food" , value: "comfort-food" },
    {label: "tilapia" , value: "tilapia" },
    {label: "austrian" , value: "austrian" },
    {label: "condiments" , value: "condiments" },
    {label: "long-grain-rice" , value: "long-grain-rice" },
    {label: "salsas" , value: "salsas" },
    {label: "japanese" , value: "japanese" },
    {label: "beijing" , value: "beijing" },
    {label: "brown-rice" , value: "brown-rice" },
    {label: "squash" , value: "squash" },
    {label: "ice-cream" , value: "ice-cream" },
    {label: "roast-beef" , value: "roast-beef" },
    {label: "beef" , value: "beef" },
    {label: "rosh-hashana" , value: "rosh-hashana" },
    {label: "vegetarian" , value: "vegetarian" },
    {label: "dessert" , value: "dessert" },
    {label: "oven" , value: "oven" },
    {label: "scallops" , value: "scallops" },
    {label: "carrots" , value: "carrots" },
    {label: "snacks" , value: "snacks" },
    {label: "lemon" , value: "lemon" },
    {label: "toddler-friendly" , value: "toddler-friendly" },
    {label: "biscuits" , value: "biscuits" },
    {label: "chicken-livers" , value: "chicken-livers" },
    {label: "smoker" , value: "smoker" },
    {label: "swiss" , value: "swiss" },
    {label: "casserole" , value: "casserole" },
    {label: "rolls" , value: "rolls" },
    {label: "steak" , value: "steak" },
    {label: "pennsylvania-dutch" , value: "pennsylvania-dutch" },
    {label: "crock-pot" , value: "crock-pot" },
    {label: "canning" , value: "canning" },
    {label: "dutch" , value: "dutch" },
    {label: "hawaiian" , value: "hawaiian" },
    {label: "spaghetti-sauce" , value: "spaghetti-sauce" },
    {label: "for-1-or-2" , value: "for-1-or-2" },
    {label: "chowders" , value: "chowders" },
    {label: "mexican" , value: "mexican" },
    {label: "cake-filling" , value: "cake-filling" },
    {label: "caribbean" , value: "caribbean" },
    {label: "jewish" , value: "jewish" },
    {label: "pineapple" , value: "pineapple" },
    {label: "onions" , value: "onions" },
    {label: "european" , value: "european" },
    {label: "rice" , value: "rice" },
    {label: "creole" , value: "creole" },
    {label: "belgian" , value: "belgian" },
    {label: "pheasant" , value: "pheasant" },
    {label: "herbs-and-spice-mix" , value: "herbs-and-spice-mix" },
    {label: "candy" , value: "candy" },
    {label: "bok-choy" , value: "bok-choy" },
    {label: "gelatin" , value: "gelatin" },
    {label: "nuts" , value: "nuts" },
    {label: "sourdough" , value: "sourdough" },
    {label: "microwave" , value: "microwave" },
    {label: "ice-cream" , value: "ice-cream" },
    {label: "chicken" , value: "chicken" },
    {label: "wild-game" , value: "wild-game" },
    {label: "pineapple" , value: "pineapple" },
    {label: "passover" , value: "passover" },
    {label: "scallops" , value: "scallops" },
    {label: "szechuan" , value: "szechuan" },
    {label: "citrus" , value: "citrus" },
    {label: "halloween" , value: "halloween" },
    {label: "food-processor" , value: "food-processor" },
    {label: "stove-top" , value: "stove-top" },
    {label: "frozen-desserts" , value: "frozen-desserts" },
    {label: "bar-cookies" , value: "bar-cookies" },
    {label: "lactose" , value: "lactose" },
    {label: "british-columbian" , value: "british-columbian" },
    {label: "pasta-shells" , value: "pasta-shells" },
    {label: "low-saturated-fat" , value: "low-saturated-fat" },
    {label: "tarts" , value: "tarts" },
    {label: "jewish" , value: "jewish" },
    {label: "picnic" , value: "picnic" },
    {label: "south-african" , value: "south-african" },
    {label: "namibian" , value: "namibian" },
    {label: "15-minutes-or-less" , value: "15-minutes-or-less" },
    {label: "pancakes" , value: "pancakes" },
    {label: "keto" , value: "keto" },
    {label: "brownies" , value: "brownies" },
    {label: "ground-beef" , value: "ground-beef" },
    {label: "a1-sauce" , value: "a1-sauce" },
    {label: "asparagus" , value: "asparagus" },
    {label: "french" , value: "french" },
    {label: "infant-baby-friendly" , value: "infant-baby-friendly" },
    {label: "jellies" , value: "jellies" },
    {label: "elk" , value: "elk" },
    {label: "persian" , value: "persian" },
    {label: "salsas" , value: "salsas" },
    {label: "tropical-fruit" , value: "tropical-fruit" },
    {label: "60-minutes-or-less" , value: "60-minutes-or-less" },
    {label: "savory" , value: "savory" },
    {label: "cheap" , value: "cheap" },
    {label: "savory-pies" , value: "savory-pies" },
    {label: "native-american" , value: "native-american" },
    {label: "curries" , value: "curries" },
    {label: "salads" , value: "salads" },
    {label: "manicotti" , value: "manicotti" },
    {label: "european" , value: "european" },
    {label: "granola" , value: "granola" },
    {label: "carrots" , value: "carrots" },
    {label: "non-alcoholic" , value: "non-alcoholic" },
    {label: "soy" , value: "soy" },
    {label: "fish" , value: "fish" },
    {label: "chicken-breasts" , value: "chicken-breasts" },
    {label: "squid" , value: "squid" },
    {label: "new-zealand" , value: "new-zealand" },
    {label: "pumpkin" , value: "pumpkin" },
    {label: "deep-fry" , value: "deep-fry" },
    {label: "oaxacan" , value: "oaxacan" },
    {label: "meat" , value: "meat" },
    {label: "german" , value: "german" },
    {label: "memorial-day" , value: "memorial-day" },
    {label: "laotian" , value: "laotian" },
 ];

}
